[installer]
modern-installation = true

[virtualenvs]
create = true
in-project = true
path = "{project-dir}/.venv"
prefer-active-python = false

[virtualenvs.options]
always-copy = true
no-pip = false
no-setuptools = false
